import Link from 'next/link';
import { notFound } from 'next/navigation';

import { Badge, Card, EmptyState, TableViewport } from '@/components/ui';
import { createTranslator } from '@/lib/i18n/messages';
import { formatBDT } from '@/lib/money';
import { getSession, requirePageCapability } from '@/lib/session';
import { db } from '@/repositories';
import { getSupplierAnalytics, parseSupplierAnalyticsFilters, UNKNOWN_SUPPLIER_ID } from '@/services/supplier-analytics';

export const dynamic = 'force-dynamic';
type RawParams = Record<string, string | string[] | undefined>;

export default async function SupplierAnalyticsDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<RawParams> }) {
  await requirePageCapability('VIEW_REPORTS');
  const [{ id }, raw, { locale }] = await Promise.all([params, searchParams, getSession()]);
  const isUnattributed = id === UNKNOWN_SUPPLIER_ID;
  const supplier = isUnattributed ? null : await db.suppliers.findById(id);
  if (!isUnattributed && !supplier) notFound();
  const filters = { ...parseSupplierAnalyticsFilters(raw), supplierId: id };
  const result = await getSupplierAnalytics(filters); const row = result.rows.find((item) => item.supplierId === id);
  const t = createTranslator(locale); const products = result.productsBySupplier.get(id) ?? []; const activity = result.activitiesBySupplier.get(id) ?? [];
  return <>
    <header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-[22px] font-semibold tracking-[-0.01em]">{supplier?.name ?? t('supplierAnalytics.notRecorded')}</h1>{supplier && !supplier.isActive && <Badge>{t('supplierAnalytics.removed')}</Badge>}</div><p className="mt-1 text-[12px] text-graphite">{t('supplierAnalytics.detailSubtitle')}</p>{supplier && <div className="mt-2 flex max-w-4xl flex-wrap gap-x-5 gap-y-1 text-[12px]"><span><strong>{t('common.phone')}:</strong> <span className="tnum">{supplier.phone ?? t('common.notRecorded')}</span></span><span><strong>{t('common.email')}:</strong> {supplier.email ?? t('common.notRecorded')}</span><span><strong>{t('common.address')}:</strong> {supplier.address ?? t('common.notRecorded')}</span></div>}</div><Link href="/suppliers/analytics" className="inline-flex h-9 shrink-0 items-center justify-center rounded-[3px] border border-graphite bg-graphite px-3.5 text-[13px] font-medium text-white transition-colors hover:border-ink hover:bg-ink">{t('supplierAnalytics.back')}</Link></header>
    {row && <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label={t('supplierAnalytics.grossPurchases')} value={formatBDT(row.grossPurchaseCost)} /><Metric label={t('supplierAnalytics.netRetained')} value={formatBDT(row.netRetainedPurchaseCost)} /><Metric label={t('supplierAnalytics.unitsReceived')} value={String(row.unitsReceived)} /><Metric label={t('supplierAnalytics.returnedCost')} value={formatBDT(row.returnedStockCost)} /><Metric label={t('supplierAnalytics.recovered')} value={formatBDT(row.recoveredAmount)} /><Metric label={t('supplierAnalytics.recoveryDifference')} value={formatBDT(row.recoveryDifference)} /><Metric label={t('supplierAnalytics.returnRate')} value={`${row.returnRate.toFixed(2)}%`} /></div>}
    <Card className="mb-4"><h2 className="border-b border-rule px-4 py-3 text-[15px] font-semibold">{t('supplierAnalytics.productBreakdown')}</h2>{products.length === 0 ? <EmptyState title={t('supplierAnalytics.noProducts')} /> : <TableViewport><table className="w-full min-w-[900px] text-[12px] [&_td]:text-center [&_th]:text-center"><thead><tr className="border-b border-rule"><th className="eyebrow px-3 py-2.5">{t('common.product')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.unitsReceived')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.grossPurchases')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.averageCost')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.returnedUnits')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.returnedCost')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.recovered')}</th></tr></thead><tbody>{products.map((item) => <tr key={item.productId} className="border-b border-rule-soft"><td className="px-3 py-3"><p className="font-medium">{item.productName}</p><p className="tnum text-[11px] text-graphite">{item.sku}</p></td><td className="tnum px-3 py-3">{item.unitsReceived}</td><td className="tnum px-3 py-3">{formatBDT(item.purchaseCost)}</td><td className="tnum px-3 py-3">{formatBDT(item.averageUnitCost)}</td><td className="tnum px-3 py-3">{item.returnedUnits}</td><td className="tnum px-3 py-3">{formatBDT(item.returnedStockCost)}</td><td className="tnum px-3 py-3">{formatBDT(item.recoveredAmount)}</td></tr>)}</tbody></table></TableViewport>}</Card>
    <Card><h2 className="border-b border-rule px-4 py-3 text-[15px] font-semibold">{t('supplierAnalytics.recentActivity')}</h2>{activity.length === 0 ? <EmptyState title={t('supplierAnalytics.noActivity')} /> : <TableViewport className="max-h-96"><table className="w-full min-w-[760px] text-[12px] [&_td]:text-center [&_th]:text-center"><thead className="sticky top-0 bg-card"><tr className="border-b border-rule"><th className="eyebrow px-3 py-2.5">{t('common.date')}</th><th className="eyebrow px-3 py-2.5">{t('supplierAnalytics.activity')}</th><th className="eyebrow px-3 py-2.5">{t('common.product')}</th><th className="eyebrow px-3 py-2.5">{t('common.quantity')}</th><th className="eyebrow px-3 py-2.5">{t('common.total')}</th><th className="eyebrow px-3 py-2.5">{t('common.reference')}</th></tr></thead><tbody>{activity.map((item) => <tr key={item.id} className="border-b border-rule-soft"><td className="tnum px-3 py-3">{new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Dhaka', day: '2-digit', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }).format(new Date(item.occurredAt))}</td><td className="px-3 py-3">{t(`supplierAnalytics.kind${item.kind}`)}</td><td className="px-3 py-3"><p>{item.productName}</p><p className="tnum text-[11px] text-graphite">{item.sku}</p></td><td className="tnum px-3 py-3">{item.quantity}</td><td className="tnum px-3 py-3">{formatBDT(item.amount)}</td><td className="tnum px-3 py-3">{item.reference ?? '—'}</td></tr>)}</tbody></table></TableViewport>}</Card>
  </>;
}

function Metric({ label, value }: { label: string; value: string }) { return <Card className="p-4"><p className="eyebrow">{label}</p><p className="tnum mt-2 text-[19px] font-semibold">{value}</p></Card>; }
